"""Audit Defense Pack — per-transaction evidence bundle PDF for LHDN/auditors."""
import io
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
)


def build_audit_pack(match: dict, bank_name: str) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, leftMargin=1.8*cm, rightMargin=1.8*cm,
                            topMargin=1.8*cm, bottomMargin=1.8*cm)
    styles = getSampleStyleSheet()
    h1 = styles["Heading1"]; h2 = styles["Heading2"]; body = styles["BodyText"]
    small = ParagraphStyle("s", parent=body, fontSize=8, textColor=colors.grey)
    mono = ParagraphStyle("m", parent=body, fontSize=8, fontName="Courier")

    p = match["proof"]; tx = match["txn"]; c = match["conversion"]
    story = []
    story.append(Paragraph(f"AUDIT EVIDENCE PACK — {p.get('reference','no-ref')}", h1))
    story.append(Paragraph(
        f"Generated {datetime.utcnow().isoformat(timespec='seconds')}Z · "
        f"Bank: {bank_name} · Confidence: {int(match['confidence']*100)}%", small))
    story.append(Spacer(1, 0.4*cm))

    sections = [
        ("§1 PAYMENT PROOF (source: client document)", [
            ("Source file", p.get("source_file","")),
            ("Payer", p.get("payer","")),
            ("Payee", p.get("payee","")),
            ("Invoice / Ref", p.get("reference","")),
            ("Original amount", f"{p.get('amount')} {p.get('currency')}"),
            ("Transaction date", p.get("date","")),
            ("Description", p.get("description","") or "—"),
        ]),
        ("§2 LOCAL BANK TRANSACTION (source: bank statement)", [
            ("Bank txn ID", tx["id"]),
            ("Date posted", tx["date"]),
            ("Amount credited", f"{tx['amount']} {tx['currency']}"),
            ("Bank narrative", tx.get("description","")),
            ("Bank reference", tx.get("reference","")),
        ]),
        ("§3 FX CONVERSION (source: ECB via frankfurter.app)", [
            ("From currency", p.get("currency","")),
            ("To currency", tx["currency"]),
            ("Rate applied", f"{c['fx_rate']:.6f}"),
            ("Rate date", p.get("date","")),
            ("Gross converted", f"{c['expected_gross']} {tx['currency']}"),
        ]),
        ("§4 BANK FEE (source: institutional fee schedule)", [
            ("Bank", bank_name),
            ("Fee rule", f"{c['fee_pct']*100:.2f}% inbound conversion"),
            ("Fee deducted", f"{c['fee_amount']} {tx['currency']}"),
            ("Net expected", f"{c['expected_net']} {tx['currency']}"),
        ]),
        ("§5 RECONCILIATION RESULT", [
            ("Actual received", f"{c['actual_received']} {tx['currency']}"),
            ("Variance vs expected",
                f"{round(c['actual_received'] - c['expected_net'], 2)} {tx['currency']}"),
            ("Variance %",
                f"{abs(c['actual_received']-c['expected_net'])/max(c['expected_net'],1e-6)*100:.3f}%"),
            ("Status", match["status"]),
            ("Tolerance applied", "2.00% (configurable)"),
        ]),
    ]
    for title, rows in sections:
        story.append(Paragraph(title, h2))
        t = Table(rows, colWidths=[5.5*cm, 11.5*cm])
        t.setStyle(TableStyle([
            ("BACKGROUND", (0,0), (0,-1), colors.HexColor("#f1f5f9")),
            ("GRID", (0,0), (-1,-1), 0.3, colors.grey),
            ("FONTSIZE", (0,0), (-1,-1), 9),
            ("VALIGN", (0,0), (-1,-1), "TOP"),
        ]))
        story.append(t)
        story.append(Spacer(1, 0.3*cm))

    story.append(Paragraph("§6 AGENT REASONING (chain of custody)", h2))
    story.append(Paragraph(match.get("reasoning",""), small))

    story.append(Spacer(1, 0.6*cm))
    story.append(Paragraph("§7 ATTESTATION", h2))
    story.append(Paragraph(
        "This evidence pack is auto-generated by the Treasury Oracle agent. "
        "All FX rates were retrieved from European Central Bank reference data "
        "via api.frankfurter.app. Bank fees are configured against the institution's "
        "published schedule. No human modification has occurred between automated "
        "ingestion and this attestation. Audit trail hash and source files are "
        "retrievable via /api/audit-pack/{recon_id}/{match_index}.", body))

    story.append(Spacer(1, 0.4*cm))
    story.append(Paragraph(
        f"<i>Document ID: AUDIT-{tx['id']}-{datetime.utcnow().strftime('%Y%m%d%H%M%S')}</i>",
        mono))

    doc.build(story)
    return buf.getvalue()
